# Generated by Django 4.1.7 on 2023-03-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_useraccount_name_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(default='Phone', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.CharField(choices=[('donator', 'Donator'), ('orphanage', 'Orphanage')], default='Orphanage', max_length=60),
        ),
    ]
