# Generated by Django 4.1.3 on 2023-03-20 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_useraccount_phone_useraccount_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user',
            new_name='user_login',
        ),
    ]
