# Generated by Django 4.1.7 on 2023-03-21 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_rename_user_useraccount_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(default='Post', max_length=60)),
                ('donated', models.DecimalField(decimal_places=2, max_digits=20)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orphanages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField(default=False)),
                ('address1', models.CharField(default='Address line 1', max_length=1024)),
                ('address2', models.CharField(default='Address line 2', max_length=1024)),
                ('zip_code', models.CharField(default='ZIP / Postal code', max_length=20)),
                ('city', models.CharField(default='City', max_length=1024)),
                ('country', models.CharField(default='Country', max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Post', max_length=60)),
                ('pic', models.ImageField(default='img/place', null=True, upload_to='img/gallery')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.orphanages')),
            ],
        ),
        migrations.CreateModel(
            name='needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Need', max_length=60)),
                ('raised', models.DecimalField(decimal_places=2, max_digits=20)),
                ('goal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(default='Description', max_length=2000, null=True)),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.orphanages')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Message', max_length=1024)),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.donations')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.orphanages')),
            ],
        ),
        migrations.CreateModel(
            name='annualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('file', models.FileField(upload_to='documents/')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.orphanages')),
            ],
        ),
    ]
