# Generated by Django 4.1.7 on 2023-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_donations_orphanages_posts_needs_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_login',
            field=models.CharField(choices=[('donator', 'Donator'), ('orphanage', 'Orphanage'), ('admin', 'Admin')], default='Orphanage', max_length=60),
        ),
    ]
