# Generated by Django 4.1.7 on 2023-03-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_useraccount_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
