# Generated by Django 4.1.7 on 2023-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_rename_first_name_useraccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needs',
            name='pic',
            field=models.ImageField(default='img/place', null=True, upload_to='img/needs'),
        ),
    ]
