# Generated by Django 4.1.7 on 2023-03-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_needs_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.needs'),
        ),
    ]
