# Generated by Django 4.1.3 on 2023-03-22 06:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_alter_donations_donator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='gallery',
        ),
        migrations.RenameField(
            model_name='donations',
            old_name='need',
            new_name='needs',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='donator',
            new_name='donor',
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2023)]),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='donations',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='Thank You for your love and support !!!', max_length=1024),
        ),
        migrations.AlterField(
            model_name='needs',
            name='goal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='needs',
            name='raised',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
