# Generated by Django 4.1.3 on 2023-03-22 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_rename_name_useraccount_namee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanages',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_login': 'orphanage'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
