# Generated by Django 4.1.7 on 2023-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_alter_donations_donator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='donator',
        ),
        migrations.RemoveField(
            model_name='donations',
            name='needs',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='orphanage',
        ),
        migrations.RemoveField(
            model_name='message',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='orphanage',
        ),
        migrations.RemoveField(
            model_name='needs',
            name='orphanage',
        ),
        migrations.RemoveField(
            model_name='orphanages',
            name='user',
        ),
        migrations.DeleteModel(
            name='annualReport',
        ),
        migrations.DeleteModel(
            name='donations',
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='needs',
        ),
        migrations.DeleteModel(
            name='orphanages',
        ),
    ]
