# Generated by Django 4.1.3 on 2023-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_remove_donations_donator_remove_donations_needs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address1',
            field=models.CharField(default='Address line 1', max_length=1024),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='address2',
            field=models.CharField(default='Address line 2', max_length=1024),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(default='City', max_length=1024),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.CharField(default='Country', max_length=300),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pic',
            field=models.ImageField(default='img/place', null=True, upload_to='img/orphanage'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='state',
            field=models.CharField(default='State', max_length=300),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='zip_code',
            field=models.CharField(default='ZIP / Postal code', max_length=20),
        ),
    ]
