# Generated by Django 4.1.3 on 2023-03-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_useraccount_address1_useraccount_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='address2',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='address1',
        ),
    ]
