# Generated by Django 4.1.3 on 2023-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_rename_address2_useraccount_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default='Address', max_length=1024),
        ),
    ]
