# Generated by Django 4.1.3 on 2023-03-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0018_alter_useraccount_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='pic',
        ),
    ]
