# Generated by Django 4.1.7 on 2023-03-22 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('donator', models.ForeignKey(limit_choices_to={'user_login': 'donator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orphanages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField(default=False)),
                ('address1', models.CharField(default='Address line 1', max_length=1024)),
                ('address2', models.CharField(default='Address line 2', max_length=1024)),
                ('zip_code', models.CharField(default='ZIP / Postal code', max_length=20)),
                ('city', models.CharField(default='City', max_length=1024)),
                ('country', models.CharField(default='Country', max_length=300)),
                ('user', models.OneToOneField(limit_choices_to={'user_login': 'orphanage'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Need', max_length=60)),
                ('raised', models.IntegerField(default=0, null=True)),
                ('goal', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(default='Description', max_length=2000, null=True)),
                ('pic', models.ImageField(default='img/place', null=True, upload_to='img/needs')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.orphanages')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Thank You for your love and support !!!', max_length=1024)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donations')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.orphanages')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Post', max_length=60)),
                ('pic', models.ImageField(default='img/place', null=True, upload_to='img/gallery')),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.orphanages')),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='needs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.needs'),
        ),
        migrations.CreateModel(
            name='annualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023)])),
                ('orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.orphanages')),
            ],
        ),
    ]
