# Generated by Django 4.1.7 on 2023-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanages',
            name='pic',
            field=models.ImageField(default='img/place', null=True, upload_to='img/orphanage'),
        ),
        migrations.AddField(
            model_name='orphanages',
            name='state',
            field=models.CharField(default='State', max_length=300),
        ),
    ]
