# Generated by Django 4.1.3 on 2023-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_alter_annualreport_orphanage_alter_gallery_orphanage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
