# Generated by Django 4.1.3 on 2023-03-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0005_message_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donations', unique=True),
        ),
    ]
