# Generated by Django 4.1.3 on 2023-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0006_alter_message_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='needs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orphanage.needs'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='orphanages',
        ),
    ]
