# Generated by Django 4.1.3 on 2023-04-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0008_remove_needs_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
