# Generated by Django 4.1.3 on 2023-04-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0010_mealdonation_delete_onedaymeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdonation',
            name='donator',
            field=models.PositiveIntegerField(),
        ),
    ]
