# Generated by Django 4.1.3 on 2023-04-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0012_alter_mealdonation_donator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_id', models.IntegerField()),
                ('day_meal_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mealdonation',
            unique_together={('orphanage_id', 'date_of_booking')},
        ),
    ]
