# Generated by Django 4.1.3 on 2023-04-12 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orphanage', '0013_meal_alter_mealdonation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='orphanage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
