# Generated by Django 4.1.3 on 2023-04-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0014_alter_meal_orphanage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donations'),
        ),
        migrations.AlterField(
            model_name='message',
            name='needs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.needs', unique=True),
        ),
    ]
