# Generated by Django 4.1.3 on 2023-04-13 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orphanage', '0017_alter_mealdonation_donator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealdonation',
            name='donator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealdonation',
            name='orphanage_id',
            field=models.PositiveIntegerField(),
        ),
    ]
