# Generated by Django 4.1.3 on 2023-04-13 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orphanage', '0018_alter_mealdonation_donator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='orphanage',
            field=models.ForeignKey(limit_choices_to={'user_login': 'orphanage'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meal',
            name='orphanage_id',
            field=models.ForeignKey(limit_choices_to={'user_login': 'orphanage'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mealdonation',
            name='donator',
            field=models.ForeignKey(limit_choices_to={'user_login': 'donator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='donor',
            field=models.ForeignKey(limit_choices_to={'user_login': 'donator'}, on_delete=django.db.models.deletion.CASCADE, to='orphanage.donations'),
        ),
    ]
