# Generated by Django 4.1.3 on 2023-04-18 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0019_alter_annualreport_orphanage_alter_meal_orphanage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
